version: '3.7'

networks:
  local:
    driver: bridge

services:

  eventstore:
    container_name: eventstore
    image: eventstore/eventstore:release-5.0.8
    networks:
      - local    
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      EVENTSTORE_EXT_HTTP_PORT: 2113
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
      PROJECTION_THREADS: 8
      EVENTSTORE_INSECURE: 'true'
      EVENTSTORE_DEV: 'true'
    restart: always
    
  order_command_api_1:
    image: order.command.api
    environment:
      - ServiceName=Service Register 1
      - EventStoreConnection=tcp://admin:changeit@eventstore:1113   
    networks:
      - local
    expose:
      - "80"
    ports:
      - "5119:80"  