version: '3.7'

networks:
  local:
    driver: bridge

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - local 
    ports:
      - 27017:27017
  eventstore:
    container_name: eventstore
    image: eventstore/eventstore:release-5.0.8
    networks:
      - local    
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      EVENTSTORE_EXT_HTTP_PORT: 2113
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
      PROJECTION_THREADS: 8
      EVENTSTORE_INSECURE: 'true'
      EVENTSTORE_DEV: 'true'
    restart: always 
    
  order.gateway.api:
    container_name: ordergatewayapi
    image: order.gateway.api
    networks:
      - local
    expose:
      - "80"
    ports:
      - "6000:80"
      
  order-command-api:
    container_name: ordercommandapi 
    image: order.command.api
    environment:
      - ServiceName= Server 1
      - EventStoreConnection=tcp://admin:changeit@eventstore:1113
      - MongoConnection=mongodb://root:password@mongodb:27017/?authSource=admin
      - MongoDatabase=OrderAggregate    
    networks:
      - local
    expose:
      - "80"

  order-query-py:
    container_name: orderquerypy
    image: order.query.py.api
    networks:
      - local
    environment:
       PORT: 5000
       FLASK_DEBUG: 1
    ports:
        - 5000:5000